acme:
  enabled: true
  remote-address: 192.168.0.108
  security:
    username: txjava
    password: 123
    roles:
      - 男主角
      - 摄影师
  myPerson:
    person:
      first-name: 张
      age: 4
      email: 471068961@qq.com
