yaml:
  str: 字符串不需要加双引号
  num: 666
  Doum: 666.88
  birth: 2000/12/10 12:23:34
  list:
    - one
    - two
    - three
  users:
    - name: 张三
      salary: 123.8
    - name: 李四
      salary: 456.3
  map: {key1: value1, key2: value2}